name: C/C++ CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install bash
      run: sudo apt install bash
    - name: install git
      run: sudo apt install git
    - name: build kunai
      run: ./debian_distros_installer.sh build